development:
  adapter: mysql2
  encoding: utf8
  database: beautboss
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: beautboss_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

staging:
  adapter: mysql2
  encoding: utf8
  database: beautboss-staging
  pool: 5
  username: root
  password: bbstaging2015
  # socket: /var/run/mysqld/mysqld.sock
  host: beautboss-staging.czn9y43ptinh.us-west-2.rds.amazonaws.com
  port: 3306