development:
  adapter: mysql2
  encoding: utf8
  database: beautboss
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: beautboss_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

# staging:
#   adapter: mysql2
#   encoding: utf8
#   database: beautboss_staging
#   pool: 5
#   username: beautboss
#   password: g4sPtHghybpjg9Ap
#   host: 
#   port: 3306

staging:
  adapter: mysql2
  encoding: utf8
  database: beautboss_staging
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: beautboss
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: 3306